config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :games do
    resources :rounds, only: %i[new create edit update destroy]
  end

  root 'home#index'
end

app/views/shared/_round_score_table.html.erb
<table class="table table-striped table-bordered mx-auto text-center align-middle" style="max-width: 1100px;">
  <thead class="table-dark border border-white text-center align-middle">
    <tr>
      <th scope="col" style="width: 200px; font-size: 1.5em;">Score</th>
      <% @game.game_players.each do |game_player| %>
        <th scope="col" style="width: 100px;"><%= game_player.player.name %></th>
      <% end %>
      <% if edit_page && @game.state_in_progress? %>
        <th scope="col" style="width: 70px;">
          <% if add_round_button %>
            <%= link_to new_game_round_path(@game), class:"text-decoration-none btn btn-empty", title: 'New Round' do %>
              <i class="bi bi-plus-square-fill text-white" style="font-size: 1.5em;"></i>&nbsp;
            <% end %>
          <% end %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @game.rounds.includes(game_player: :player).sort_by(&:position).reverse.each do |round| %>
      <tr>
        <td class="border border-dark">
          <strong><%= Round.round_types[round.round_type] %></strong><br/>
          <span style="font-size: 0.8em;"><%= round.game_player.player.name %></span>
        </td>
        <% @game.game_players.each do |game_player| %>
          <td class="border border-dark">
            <% player_scores = round.scores || {} %>
            <% player_score = player_scores[game_player.id.to_s] if player_scores.present? %>
            <%= player_score || 0 %>
          </td>
        <% end %>
        <% if edit_page && @game.state_in_progress? %>
          <td class="border border-dark">
            <div class="btn-group game-actions">
              <%= link_to edit_game_round_path(@game, round), class:"text-decoration-none btn btn-empty btn-sm", title: 'Edit' do %>
                <i class="bi bi-pencil-fill"></i>&nbsp;&nbsp;
              <% end %>
              <%= button_to game_round_path(@game, round), method: :delete, class:"btn btn-empty btn-sm", title: 'Delete' do %>
                <i class="bi bi-trash3-fill"></i>
              <% end %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_round_total_score_table.html.erb
<table class="table table-bordered mx-auto text-center align-middle" style="max-width: 1100px;">
  <tbody class="border border-dark border-4 fs-3 fw-bold">
    <tr>
      <td class="border border-dark border-4" scope="col" style="width: 200px;">Total</td>
      <% @game.game_players.each do |game_player| %>
        <td class="border border-dark border-4" scope="col" style="width: 100px; text-align: center"><%= @player_totals[game_player.id] || 0 %></td>
      <% end %>
      <% if edit_page && @game.state_in_progress? %>
        <td class="border border-dark border-4" scope="col" style="width: 70px;"></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/shared/_round_type_table.html.erb
<table class="table table-striped table-bordered mx-auto text-center align-middle" style="max-width: 1100px;">
  <thead class="table-dark border border-white text-center align-middle">
    <tr>
      <th scope="col" style="width: 200px; font-size: 1.5em;">Rounds</th>
      <% @game.game_players.each do |game_player| %>
        <th scope="col" style="width: 100px;"><%= game_player.player.name %></th>
      <% end %>
      <% if edit_page && @game.state_in_progress? %>
        <th scope="col" style="width: 70px;"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% Round.round_types.each do |round_type_key, round_type_value| %>
      <tr>
        <td class="border border-dark">
          <strong><%= round_type_value %></strong><br/>
          <span style="font-size: 0.8em;"><%= Round::ROUND_DESCRIPTION[round_type_key.to_sym] %></span>
        </td>
        <% @game.game_players.each do |game_player| %>
          <% round_played = game_player.rounds.any? { |round| round.round_type == round_type_key } %>
          <td class="border border-dark <%= 'bg-info' if round_played %>"></td>
        <% end %>
        <% if edit_page && @game.state_in_progress? %>
          <td class="border border-dark"></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_table_header.html.erb
<th>
  <%= link_to header_name, {
    sort: sort_key,
    sort_dir: @sort == sort_key && @sort_dir == 'asc' ? 'desc' : 'asc'
  }, class: 'plain-link' %>
  <% if @sort == sort_key %>
    <% if @sort_dir == 'asc' %>
      <i class="bi bi-caret-down-fill"></i>
    <% else %>
      <i class="bi bi-caret-up-fill"></i>
    <% end %>
  <% end %>
</th>