config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :games do
    resources :rounds, only: %i[new create edit update destroy]
  end

  root 'home#index'
end

app/models/game.rb
class Game < ApplicationRecord
  include Sortable

  MAX_PLAYERS_PER_GAME = 8
  MIN_PLAYERS_PER_GAME = 3
  VALID_TRANSITIONS = {
    created: %i[created in_progress canceled],
    in_progress: %i[in_progress completed canceled],
    completed: %i[completed],
    canceled: %i[canceled]
  }.freeze

  after_update :reorder_game_players

  validate :valid_state_transition, on: :update
  validates :game_players, length: {
    maximum: MAX_PLAYERS_PER_GAME,
    message: "There can be a maximum of #{MAX_PLAYERS_PER_GAME} players in a game."
  }
  validates :game_players, length: {
    minimum: MIN_PLAYERS_PER_GAME,
    message: "Minimum number of players to start the game is #{MIN_PLAYERS_PER_GAME}"
  }, if: -> { state_in_progress? }

  has_many :game_players, -> { order(position: :asc) }, dependent: :delete_all, inverse_of: :game
  has_many :players, through: :game_players
  has_many :rounds, through: :game_players

  accepts_nested_attributes_for :game_players

  enum state: {
    created: 'created',
    in_progress: 'in_progress',
    completed: 'completed',
    canceled: 'canceled'
  }, _prefix: true

  def can_start?
    state_created? && game_players.size.between?(MIN_PLAYERS_PER_GAME, MAX_PLAYERS_PER_GAME)
  end

  def can_complete?
    state_in_progress?
  end

  def can_cancel?
    state_created? || state_in_progress?
  end

  def self.allowed_sort_columns
    %w[created_at id state]
  end

  def self.default_sort_column
    'created_at'
  end

  def self.default_direction
    'desc'
  end

  private

  def valid_state_transition
    return if VALID_TRANSITIONS[state_was.to_sym].include?(state.to_sym)

    errors.add(:state, 'invalid state transition')
  end

  def reorder_game_players
    return if game_players.pluck(:position).sort == [*1..game_players.size]

    game_players.each_with_index do |game_player, index|
      game_player.update(position: index + 1)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[edit update destroy]

  def index
    @sort = params[:sort] || Game.default_sort_column
    @sort_dir = params[:sort_dir] || Game.default_direction

    @games = Game.includes(:rounds, :game_players).all.sort_table(@sort, @sort_dir)
    @pagy, @games = pagy(@games)
  end

  def show
    @game = Game.includes(:players, game_players: :rounds).find(params[:id])
    player_total_score
  end

  def new
    @game = Game.new
  end

  def edit
    player_total_score
  end

  def create
    @game = Game.new(create_game_params)

    if @game.save
      redirect_to games_url, notice: 'Game was successfully created.'
    else
      flash.now[:notice] = @game.errors.map(&:message).join(' ')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @game.update(update_game_params)
      redirect_to edit_game_url(@game), notice: 'Game was successfully updated.'
    else
      flash.now[:notice] = @game.errors.map(&:message).join(' ')
      @game.reload
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @game.game_players.destroy_all
    @game.destroy
    redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private

  def set_game
    @game = Game.includes(:players).find(params[:id])
  end

  def create_game_params
    params.require(:game).permit(player_ids: [])
  end

  def update_game_params
    if @game.state_created?
      params.require(:game).permit(:state, player_ids: [], game_players_attributes: %i[id position])
    else
      params.require(:game).permit(:state)
    end
  end

  def player_total_score
    @player_totals = {}

    @game.game_players.each do |player|
      total_score = @game.rounds.sum do |round|
        player_scores = round.scores || {}
        player_scores[player.id.to_s].to_i
      end

      @player_totals[player.id] = total_score
    end
  end
end

app/views/games/_action_buttons.html.erb
<div class="btn-group game-actions">
  <%# Show start_game button %>
  <%= button_to game_path(game, { game: { state: :in_progress }, page: params[:page] }),
                method: :patch,
                disabled: !game.can_start?,
                title: 'Start',
                class:"text-decoration-none btn btn-empty btn-sm" do %>
    <i class="bi bi-play-fill"></i>&nbsp;
  <% end %>

  <%# Show cancel_game button %>
  <%= button_to game_path(game, { game: { state: :canceled }, page: params[:page] }),
                method: :patch,
                disabled: !game.can_cancel?,
                title: 'Cancel',
                class:"text-decoration-none btn btn-empty btn-sm" do %>
    <i class="bi bi-x-circle-fill"></i>&nbsp;
  <% end %>

  <%# Show completed_game button %>
  <%= button_to game_path(game, { game: { state: :completed }, page: params[:page] }),
                method: :patch,
                disabled: !game.can_complete?,
                title: 'Complete',
                class:"text-decoration-none btn btn-empty btn-sm" do %>
    <i class="bi bi-check-circle-fill"></i>&nbsp;
  <% end %>

  <%= link_to game_path(game), class:"text-decoration-none btn btn-empty btn-sm", title: 'View' do %>
    <i class="bi bi-eye-fill"></i>&nbsp;
  <% end %>
  <%= link_to edit_game_path(game), class:"text-decoration-none btn btn-empty btn-sm", title: 'Edit' do %>
    <i class="bi bi-pencil-fill"></i>&nbsp;
  <% end %>
  <%= button_to game_path(game), method: :delete, class:"btn btn-empty btn-sm", title: 'Delete' do %>
    <i class="bi bi-trash3-fill"></i>&nbsp;
  <% end %>
</div>

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <div><%= game.state %></div>
  <br/>
</div>

app/views/games/_game_table.html.erb
<table class="table table-striped table-hover table-sm">
  <thead class="table-dark table-bordered ">
    <tr style="text-align: left">
      <%= render 'shared/table_header', header_name: 'Game Number', sort_key: 'id' %>
      <%= render 'shared/table_header', header_name: 'State', sort_key: 'state' %>
      <th scope="col">Players</th>
      <%= render 'shared/table_header', header_name: 'Created At', sort_key: 'created_at' %>
      <th scope="col">Rounds</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody style="text-align: left">
    <% @games.each do |game| %>
      <tr>
        <td scope="row"><%= game.id.split("-").first %></td>
        <td scope="row"><%= game.state.humanize %></td>
        <td scope="row"><%= game.game_players.size %>/<%= Game::MAX_PLAYERS_PER_GAME %></td>
        <td scope="row"><%= time_ago_in_words(game.created_at) %></td>
        <td scope="row"><%= game.rounds.size %>/<%= Round.round_types.size * game.game_players.size %></td>
        <td scope="row"><%= render 'games/action_buttons', game: game %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/_gametable.html.erb
<table class="table table-striped table-hover table-sm">
  <thead class="table-dark table-bordered ">
    <tr style="text-align: center">
      <th>
        <%= link_to "Game Number", {
          sort: 'id',
          sort_dir: @sort == 'id' && @sort_dir == 'asc' ? 'desc' : 'asc'
        }, class: 'plain-link' %>
        <%= render 'games/sortingarrows' if @sort == 'id' %>
      </th>
      <th>
        <%= link_to "State", {
          sort: 'state',
          sort_dir: @sort == 'state' && @sort_dir == 'asc' ? 'desc' : 'asc'
        }, class: 'plain-link' %>
        <%= render 'games/sortingarrows' if @sort == 'state' %>
      </th>
      <th>
        <%= link_to "Created At", {
          sort: 'created_at',
          sort_dir: @sort == 'created_at' && @sort_dir == 'asc' ? 'desc' : 'asc'
        }, class: 'plain-link' %>
        <%= render 'games/sortingarrows' if @sort == 'created_at' %>
      </th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody style="text-align: center">
    <% @games.each do |game| %>
      <tr>
        <td scope="row"><%= game.id.split("-").first %></td>
        <td scope="row"><%= game.state.humanize %></td>
        <td scope="row"><%= time_ago_in_words(game.created_at) %></td>
        <td scope="row">
          <div class="btn-group">
            <%= link_to game_path(game), class:"text-decoration-none" do %>
              <i class="bi bi-eye-fill" style="font-size: 1.2rem; color: blue;"></i>&nbsp;
            <% end %>
            <%= link_to edit_game_path(game), class:"text-decoration-none" do %>
              <i class="bi bi-pencil-fill" style="font-size: 1.2rem; color: blue;"></i>&nbsp;
            <% end %>
            <%= button_to game_path(game), method: :delete, class:"text-decoration-none", class:"btn btn-empty btn-sm" do %>
              <i class="bi bi-trash3-fill" style="color: blue;"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/edit.html.erb
<h1>
  <p style="float: left;">
    Edit Game <%= @game.id.split("-").first %>
      <span class="badge rounded-pill bg-info"><%= @game.state.humanize %></span>
    </a>
  </p>
  <p style="float: right;"><%= link_to "Back to games", games_path, class: "btn btn-primary" %></p>
</h1>

<%= form_with(model: @game, local: true) do |form| %>
  <% if @game.state_created? %>
    <table class="table table table-striped table-hover table-sm mx-auto" style="max-width: 1100px;">
      <thead class="table-dark">
        <tr style="text-align: left">
          <th scope="col">Selected Players</th>
          <th scope="col">Position</th>
          <th scope="col">Unselected Players</th>
          <th scope="col">Created</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody style="text-align: left">
        <tr>
          <td>
            <div>
              <%= form.collection_check_boxes :player_ids, @game.game_players, :player_id, :name_with_position do |f| %>
                <div>
                  <%= f.check_box %>
                  <%= f.label %>
                </div>
              <% end %>
            </div>
          </td>
          <td scope="row">
            <table class="score-table">
              <tbody>
                <%= form.fields_for :game_players do |f| %>
                  <tr>
                    <td><%= f.object.player.name %></td>
                    <td><%= f.number_field :position, min: 1, max: @game.game_players.size%></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </td>
          <td>
            <div>
              <%= form.collection_check_boxes :player_ids, Player.where.not(id: @game.players.pluck(:id)), :id, :name do |f|%>
                <div>
                  <%= f.check_box %>
                  <%= f.label %>
                </div>
              <% end %>
            </div>
          </td>
          <td scope="row"><%= time_ago_in_words(@game.created_at) %></td>
          <td scope="row"><%= render 'games/action_buttons', game: @game %></td>
        </tr>
      </tbody>
    </table>

    <div class="d-flex justify-content-center">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% else %>
    <table class="table table table-striped table-hover table-sm mx-auto" style="max-width: 1100px;">
      <thead class="table-dark text-center align-middle">
        <tr>
          <th scope="col">Created</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="text-center align-middle">
        <tr>
          <td scope="row"><%= time_ago_in_words(@game.created_at) %></td>
          </td>
          <td scope="row"><%= render 'games/action_buttons', game: @game %></td>
        </tr>
      </tbody>
    </table>
    <%= render 'shared/round_type_table', edit_page: true %>
    <%= render 'shared/round_total_score_table', edit_page: true %>
    <%= render 'shared/round_score_table', edit_page: true, add_round_button: true %>
  <% end %>
<% end %>

app/views/games/index.html.erb
<h1>
  <p style="float: left;">Games</p>
  <p style="float: right;"><%= link_to "New game", new_game_path, class: "btn btn-primary" %></p>
</h1>

<br/><br/><br/>
<% if @games.any? %>
  <%== pagy_info(@pagy, item_name: 'games'.pluralize(@pagy.count)) %>

  <%= render 'games/game_table' %>

  <% if @pagy.count > Pagy::DEFAULT[:items] %>
    <%== pagy_bootstrap_nav(@pagy) %>
  <% end %>
<% else %>
  <h5 class="text-center">No games yet!</h5>
<% end %>

app/views/games/new.html.erb
<h1>
  <p style="float: left;">
    New Game
  </p>
  <p style="float: right;"><%= link_to "Back to games", games_path, class: "btn btn-primary" %></p>
</h1>

<%= form_with(model: @game, local: true) do |form| %>
  <table class="table table table-striped table-hover table-sm mx-auto" style="max-width: 1100px;">
    <thead class="table-dark">
      <tr style="text-align: left">
        <th scope="col">Players</th>
      </tr>
    </thead>
    <tbody style="text-align: left">
      <tr>
        <td scope="row">
          <% if Player.all.any? %>
            <div>
              <%= form.collection_check_boxes :player_ids, Player.all, :id, :name do |b| %>
                <div>
                  <%= b.check_box %>
                  <%= b.label %>
                </div>
              <% end %>
            </div>
          <% else %>
            No players created yet!
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= form.submit 'Create Game', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/games/show.html.erb
<h1>
  <p style="float: left;">
    Game <%= @game.id.split("-").first %>
    <a class="d-inline-flex align-items-center mb-2 text-body-emphasis text-decoration-none" href="/" aria-label="Bootstrap">
      <span class="badge rounded-pill bg-info"><%= @game.state.humanize %></span>
    </a>
  </p>
  <p style="float: right;"><%= link_to "Back to games", games_path, class: "btn btn-primary" %></p>
</h1>

<table class="table table table-striped table-hover table-sm mx-auto" style="max-width: 1100px;">
  <thead class="table-dark text-center align-middle">
    <tr>
      <% if @game.state_created? %>
        <th scope="col">Players</th>
      <% end %>
      <th scope="col">Created</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody class="text-center align-middle">
    <tr>
      <% if @game.state_created? %>
        <td scope="row">
            <% @game.players.each do |player| %>
              <%= player.name %><br>
            <% end %>
        </td>
      <% end %>
      <td scope="row"><%= time_ago_in_words(@game.created_at) %></td>
      </td>
      <td scope="row"><%= render 'games/action_buttons', game: @game %></td>
    </tr>
  </tbody>
</table>

<% if !@game.state_created? %>
  <%= render 'shared/round_type_table', edit_page: false %>
  <%= render 'shared/round_total_score_table', edit_page: false %>
  <%= render 'shared/round_score_table', edit_page: false, add_round_button: true %>
<% end %>