config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :games do
    resources :rounds, only: %i[new create edit update destroy]
  end

  root 'home#index'
end

app/models/player.rb
class Player < ApplicationRecord
  include Sortable

  has_many :game_players, -> { order(position: :asc) }, dependent: :destroy, inverse_of: :player
  has_many :games, through: :game_players

  validates :name, presence: true, length: { maximum: 30 }

  def self.allowed_sort_columns
    %w[name]
  end

  def self.default_sort_column
    'name'
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[show edit update destroy]

  # GET /players or /players.json
  def index
    @sort = params[:sort] || Player.default_sort_column
    @sort_dir = params[:sort_dir] || Player.default_direction

    @players = Player.all.sort_table(@sort, @sort_dir)
    @pagy, @players = pagy(@players)
  end

  # GET /players/1 or /players/1.json
  def show; end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit; end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to players_url, notice: 'Player was successfully created.'
    else
      flash.now[:notice] = @player.errors.map(&:message).join(' ')
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    if @player.update(player_params)
      redirect_to player_url(@player), notice: 'Player was successfully updated.'
    else
      flash.now[:notice] = @player.errors.map(&:message).join(' ')
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/views/players/_form.html.erb
<%= form_with(model: player, class: "table w-100") do |form| %>
  <div class="d-block rounded-3 border border-secondary outline-none px-3 py-2">
    &nbsp;
    <%= player.id&.split("-")&.first %>
  </div>
  <div>
    <%= form.text_field :name, class: "d-block rounded-3 border border-secondary outline-none px-3 py-2" %>
    <%= inline_error_for(:name, player) %>
  </div>
  <div>
    <%= link_to "Cancel", players_path, class: "btn btn-light d-inline-block border border-secondary h-100" %>
    <%= form.submit class: "btn btn-light d-inline-block border border-secondary h-100" %>
  </div>
<% end %>

app/views/players/_player.html.erb
<%= turbo_frame_tag player do %>
  <div class="table w-100">
    <div><%= player.id.split('-').first %></div>
    <div><%= player.name %></div>
    <div>
      <%= link_to "Edit", edit_player_path(player), class: "btn btn-light d-inline-block border-secondary h-100" %>
      <%= button_to "Delete", player_path(player),
                    method: :delete,
                    class: "btn btn-light d-inline-block border-secondary h-100",
                    form_class: 'd-inline-block',
                    form: { data: { turbo_confirm: 'Are you sure?' }} %>
    </div>
  </div>
<% end %>

app/views/players/_player_table.html.erb
<table class="table table table-striped table-hover table-sm">
  <thead class="table-dark">
    <tr style="text-align: left">
      <%= render 'shared/table_header', header_name: 'Name', sort_key: 'name' %>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody style="text-align: left">
    <% @players.each do |player| %>
      <tr>
        <td scope="row"><%= player.name %></td>
        <td scope="row">
          <div class="btn-group">
            <%= link_to player_path(player), class:"text-decoration-none btn btn-empty btn-sm", style: "padding: 0.1rem !important;" do %>
              <i class="bi bi-eye-fill" style="color: #0d6efd;"></i>&nbsp;
            <% end %>
            <%= link_to edit_player_path(player), class:"text-decoration-none btn btn-empty btn-sm", style: "padding: 0.1rem !important;" do %>
              <i class="bi bi-pencil-fill" style="color: #0d6efd;"></i>&nbsp;
            <% end %>
            <%= button_to player_path(player), method: :delete, class:"btn btn-empty btn-sm", style: "padding: 0.1rem !important;" do %>
              <i class="bi bi-trash3-fill" style="color: #0d6efd;"></i>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/create.turbo_stream.erb
<%= turbo_stream.prepend "players", @player %>
<%= turbo_stream.update Player.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/players/destroy.turbo_stream.erb
<%= turbo_stream.remove @player %>
<%= render_turbo_stream_flash_messages %>

app/views/players/edit.html.erb
<h1>
  <p style="float: left;">Editing player - <%= @player.name %></p>
  <p style="float: right;"><%= link_to "Back to players", players_path, class: "btn btn-primary" %></p>
</h1>
<br/><br/>
<%= form_with model: @player, url: player_path(@player), method: :put do |form| %>
  <br/>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <%= form.text_field :name, class: "form-control", id: "name" %>
    <br/>
    <%= form.submit 'Save', class:"btn btn-primary" %>
  </div>
<% end %>

app/views/players/index.html.erb
<h1>
  <p style="float: left;">Players</p>
  <p style="float: right;"><%= link_to "New player", new_player_path, class: "btn btn-primary" %></p>
</h1>

<br/><br/><br/>
<% if @players.any? %>
  <%== pagy_info(@pagy, item_name: 'games'.pluralize(@pagy.count)) %>

  <%= render 'player_table' %>

  <% if @pagy.count > Pagy::DEFAULT[:items] %>
    <%== pagy_bootstrap_nav(@pagy) %>
  <% end %>
<% else %>
  <h5 class="text-center">No players yet!</h5>
<% end %>

app/views/players/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to players"), players_path %>

  <div class="header">
    <h1>New player</h1>
  </div>

  <%= turbo_frame_tag @player do %>
    <%= render "form", player: @player %>
  <% end %>
</main>

app/views/players/show.html.erb
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h2 class="card-title"><%= @player.name %></h2>
    <p class="card-text">Here will be extra data, when available.</p>
    <div class="btn-group">
      <%= link_to "Edit", edit_player_path(@player), class:"btn btn-primary" %>&nbsp;
      <%= link_to "Back to players", players_path, class: "btn btn-primary" %>&nbsp;
      <%= button_to "Destroy", @player, method: :delete, class:"btn btn-danger" %>
    </div>
  </div>
</div>

app/views/players/update.turbo_stream.erb
<%= turbo_stream.replace @player %>
<%= render_turbo_stream_flash_messages %>